### ISSUE TITLE
Fatal error: Uncaught TypeError: Illegal offset type in isset or empty / type E_ERROR with [pmpro_member] 

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/paid-memberships-pro#2617]
**Describe the bug**
A critical error shows on a page using [pmpro_member]. 

**To Reproduce**
Steps to reproduce:
1. A test site with an **Invoice** user field and a different site had two fields. 
![image](https://github.com/strangerstudios/paid-memberships-pro/assets/4752949/3d055c5b-3cd7-4e13-8a17-994291708934)
2. Go to a page
4. Add [pmpro_member] 
5. After adding, you will see this error output: 
```
Fatal error: Uncaught TypeError: Illegal offset type in isset or empty in /wp-content/plugins/paid-memberships-proa/includes/fields.php:1676 

Stack trace: 
#0 /public/wp-content/plugins/paid-memberships-proa/shortcodes/pmpro_member.php(135): pmpro_get_label_for_user_field_value(NULL, Array) 
#1 /public/wp-includes/shortcodes.php(395): pmpro_member_shortcode('', '', 'pmpro_member') 
#2 [internal function]: do_shortcode_tag(Array) 
#3 /public/wp-includes/shortcodes.php(235): preg_replace_callback('/\\[(\\[?)(pmpro_...', 'do_shortcode_ta...', '[pmpro_member]\n') 
#4 /public/wp-includes/class-wp-hook.php(310): do_shortcode('[pmpro_member]\n') 
#5 /public/wp-includes/plugin.php(205): WP_Hook->apply_filters('[pmpro_member]\n', Array) 
#6 /public/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(1864): apply_filters('the_content', '<!-- wp:shortco...') 
#7 /public/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(569): WP_REST_Posts_Controller->prepare_item_for_response(Object(WP_Post), Object(WP_REST_Request)) 
#8 /public/wp-includes/rest-api/class-wp-rest-server.php(1188): WP_REST_Posts_Controller->get_item(Object(WP_REST_Request)) 
#9 /public/wp-includes/rest-api/class-wp-rest-server.php(1035): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wp/v2/pages/(?...', Array, NULL) 
#10 /public/wp-includes/rest-api.php(545): WP_REST_Server->dispatch(Object(WP_REST_Request)) #11 /public/wp-includes/rest-api.php(2911): rest_do_request(Object(WP_REST_Request)) 
#12 [internal function]: rest_preload_api_request(Array, '/wp/v2/pages/12...') 
#13 /public/wp-includes/block-editor.php(743): array_reduce(Array, 'rest_preload_ap...', Array) 
#14 /public/wp-admin/edit-form-blocks.php(77): block_editor_rest_api_preload(Array, Object(WP_Block_Editor_Context)) 
#15 /public/wp-admin/post.php(187): require('/Users/michaelb...') 
#16 {main} thrown in /public/wp-content/plugins/paid-memberships-proa/includes/fields.php on line 1676
```

**Expected behavior**
There should not be an error.

This came up in ticket 482012 with a similar error:

```
An error of type E_ERROR was caused in line 1676 of the file /home/wp-content/plugins/paid-memberships-pro/includes/fields.php. Error message: Uncaught TypeError: Illegal offset type in isset or empty in /home/wp-content/plugins/paid-memberships-pro/includes/fields.php:1676
Stack trace:
#0 /home/wp-content/plugins/paid-memberships-pro/shortcodes/pmpro_member.php(135): pmpro_get_label_for_user_field_value(NULL, Array)
#1 /home/wp-includes/shortcodes.php(395): pmpro_member_shortcode(”, ”, ‘pmpro_member’)
#2 [internal function]: do_shortcode_tag(Array)
#3 /home//wp-includes/shortcodes.php(235): preg_replace_callback(‘/\\[(\\[?)(pmpro_…’, ‘do_shortcode_ta…’, ‘\n
```

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Paid Memberships Pro 2.12.2, WordPress 6.3.1, PHP 7.4.30, 8.0.29, and 8.1.17
```
</details>

**Comment by MaximilianoRicoTabo** [comment]
this doesn't reproduce anymore with the fix submitted in this PR https://github.com/strangerstudios/paid-memberships-pro/pull/2622 

Improvements i see we might want to add to this shortcode though.

- Let users add in a single shortcut a set of fields instead of single.
- Let users include fields labels within the shortcode (a boolean attribute ?)
- Let users decide how to show those fields that doesn't find aything in the DB. Currently we show nothing.

@ideadude

**Comment by MaximilianoRicoTabo** [comment]
should we close this one too @ideadude @michaelbeil  ? I think we fixed with https://github.com/strangerstudios/paid-memberships-pro/pull/2622

**Comment by michaelbeil** [comment]
yep. weird, the merge should've closed it and it was fixed in my testing.
